

name: Run UI Java+Playwright Automation Tests

on: [push]

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create and set properties file
        run: | 
          touch .env
          echo VALID_USERNAME=${{ secrets.VALID_USERNAME }} >> .env
          echo VALID_PASSWORD=${{ secrets.VALID_PASSWORD }} >> .env
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'
      - name: Run tests with Maven
        run: mvn test -Dgroups=smoke
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GH_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
