

name: Run UI Java+Playwright Automation Tests

on: [push]

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create and set properties file
        env:
          VALID_USERNAME: ${{ secrets.VALID_USERNAME }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
        run: | 
          touch ./env
          echo "VALID_USERNAME=$VALID_USERNAME" >> ./env
          echo "VALID_PASSWORD=$VALID_PASSWORD" >> ./env
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'
      - name: Run tests with Maven
        run: mvn test -Dgroups=smoke
