

name: Run UI Java+Playwright Automation Tests

on: [push]

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create and set properties file
        run: | 
          touch .env
          echo VALID_USERNAME=${{ secrets.VALID_USERNAME }} >> .env
          echo VALID_PASSWORD=${{ secrets.VALID_PASSWORD }} >> .env
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'
      - name: Create allure results folder
        uses: actions/checkout@v3
        run: |
          allure generate allure-results --clean -o allure-results
      - name: Download report
        uses: actions/upload-artifact@v3
        with:
          name: allure-results.zip
          path: allure-results/*

  slack-notifications:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: testing
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Build status
          SLACK_MESSAGE: ':white_check_mark: FrontEnd build status: Success'
