

name: Run UI Java+Playwright Automation Tests

on: [push]

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create and set properties file
        run: | 
          touch .env
          echo VALID_USERNAME=${{ secrets.VALID_USERNAME }} >> .env
          echo VALID_PASSWORD=${{ secrets.VALID_PASSWORD }} >> .env
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'
      - name: Run tests with Maven
        run: mvn test -Dgroups=smoke
      - name: Send Results and Generate Allure Report
        uses: Xotabu4/send-to-allure-server-action@1
        if: ${{ always() }}
        with:
          allure-server-url: 'http://my-allure-server.com:5001/'

  slack-notifications:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: testing
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Build status
          SLACK_MESSAGE: ':white_check_mark: FrontEnd build status: Success'
